// 主要なタイムゾーンリスト
export const TIMEZONES = [
  { value: 'UTC', label: 'UTC (協定世界時)' },
  { value: 'Asia/Tokyo', label: 'Asia/Tokyo (日本標準時)' },
  { value: 'Asia/Shanghai', label: 'Asia/Shanghai (中国標準時)' },
  { value: 'Asia/Hong_Kong', label: 'Asia/Hong_Kong (香港標準時)' },
  { value: 'Asia/Singapore', label: 'Asia/Singapore (シンガポール標準時)' },
  { value: 'Asia/Seoul', label: 'Asia/Seoul (韓国標準時)' },
  { value: 'Asia/Dubai', label: 'Asia/Dubai (UAE標準時)' },
  { value: 'Asia/Kolkata', label: 'Asia/Kolkata (インド標準時)' },
  { value: 'Europe/London', label: 'Europe/London (GMT)' },
  { value: 'Europe/Paris', label: 'Europe/Paris (CET)' },
  { value: 'Europe/Berlin', label: 'Europe/Berlin (CET)' },
  { value: 'Europe/Rome', label: 'Europe/Rome (CET)' },
  { value: 'Europe/Madrid', label: 'Europe/Madrid (CET)' },
  { value: 'Europe/Moscow', label: 'Europe/Moscow (MSK)' },
  { value: 'America/New_York', label: 'America/New_York (EST/EDT)' },
  { value: 'America/Chicago', label: 'America/Chicago (CST/CDT)' },
  { value: 'America/Denver', label: 'America/Denver (MST/MDT)' },
  { value: 'America/Los_Angeles', label: 'America/Los_Angeles (PST/PDT)' },
  { value: 'America/Toronto', label: 'America/Toronto (EST/EDT)' },
  { value: 'America/Vancouver', label: 'America/Vancouver (PST/PDT)' },
  { value: 'America/Sao_Paulo', label: 'America/Sao_Paulo (BRT)' },
  { value: 'America/Mexico_City', label: 'America/Mexico_City (CST)' },
  { value: 'Australia/Sydney', label: 'Australia/Sydney (AEDT)' },
  { value: 'Australia/Melbourne', label: 'Australia/Melbourne (AEDT)' },
  { value: 'Pacific/Auckland', label: 'Pacific/Auckland (NZDT)' },
  { value: 'Pacific/Honolulu', label: 'Pacific/Honolulu (HST)' },
];
